version: "3.9"
services:
  ddng-db:
    hostname: "ddng-db"
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  ddng-mq:
    hostname: "ddng-mq"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"